=== sergarsas/PractiquesXML/P2/factura.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT facturas (factura+)>
<!ELEMENT factura (emisor, cliente, detalle)>
<!ELEMENT emisor (nom, CIF, telefono)>
<!ELEMENT cliente (nom, CIF, telefono)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT CIF (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT detalle (articulo+)>
<!ELEMENT articulo (descripcion, cantidad, oferta, PVP)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT oferta EMPTY>
<!ELEMENT PVP (#PCDATA)>
<!ATTLIST factura
    numero id #REQUIRED
    fecha CDATA #REQUIRED>
<!ATTLIST articulo
    codi id #REQUIRED
    tipo (Libro | DVD | Varios) "Varios" #IMPLIED>
<!ATTLIST detalle importe CDATA #REQUIRED>

=== sergarsas/PractiquesXML/P2/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "P2/factura.dtd">
<facturas>
    <factura numero="27" fecha="18/12/2025">
        <emisor>
            <nom>Librería Pérez</nom>
            <CIF>44555666B</CIF>
            <telefono>777888999</telefono>
        </emisor>
        <cliente>
            <nom>Biblioteca Txantrea</nom>
            <CIF>33111222A</CIF>
            <telefono>333999444</telefono>
        </cliente>
        <detalle importe="85€">
            <articulo codi="AW7" tipo="Libro">
                <descripcion>Analítica Web 2.0</descripcion>
                <cantidad>1</cantidad>
                <oferta>SI</oferta>
                <PVP>25€</PVP>
            </articulo>
            <articulo codi="CP5" tipo="DVD">
                <descripcion>Curso de HTML</descripcion>
                <cantidad>2</cantidad>
                <oferta></oferta>
                <PVP>30€</PVP>
            </articulo>
        </detalle>
    </factura>
</facturas>
