=== sergarsas/PractiquesXML/P1/aeroport.dtd
<?xml version="1.0" encoding="UTF-8" ?>รง
<!ELEMENT aeroport (nom, vol+, data)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT vol (diari, origen, desti, hora_eixida, hora_arribada)>
<!ELEMENT diari EMPTY>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT desti (#PCDATA)>
<!ELEMENT hora_eixida (#PCDATA)>
<!ELEMENT hora_arribada (#PCDATA)>
<!ATTLIST vol codi id #REQUIRED>
<!ATTLIST vol estat (R | C | E) "E">
<!ELEMENT data (#PCDATA)>

=== sergarsas/PractiquesXML/P1/aeroport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeroport SYSTEM "P1/aeroport.dtd">

<aeroport>
    <nom>JFK</nom>
    <vol codi="V22" estat="R">
        <diari>SI</diari>
        <origen>New York</origen>
        <desti>Chicago</desti>
        <hora_eixida>9:30</hora_eixida>
        <hora_arribada>11:30</hora_arribada>
    </vol>
    <vol codi="V23" estat="C">
        <diari></diari>
        <origen>New York</origen>
        <desti>Miami</desti>
        <hora_eixida>10:15</hora_eixida>
        <hora_arribada>11:15</hora_arribada>
    </vol>
    <data>20/12/2025</data>
</aeroport>
